{
    "type": "bundle",
    "id": "bundle--41956948-e30f-4067-9b86-fcf2e339d8ee",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--61cf9ad1-75b5-4d52-b7c9-f78789577f26",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-11T01:54:14.461754Z",
            "modified": "2025-04-11T01:54:14.461754Z",
            "name": "CVE-2025-32699",
            "description": "Vulnerability in Wikimedia Foundation MediaWiki, Wikimedia Foundation Parsoid.This issue affects MediaWiki: before 1.39.12, 1.42.6, 1.43.1; Parsoid: before 0.16.5, 0.19.2, 0.20.2.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32699"
                }
            ]
        }
    ]
}