{
    "type": "bundle",
    "id": "bundle--4929b01e-15a0-4803-b346-e04ee95c3679",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--f310d85a-fb3d-420e-affa-200f95de5ac7",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-06-19T00:17:37.855445Z",
            "modified": "2024-06-19T00:17:37.855445Z",
            "name": "CVE-2024-36975",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nKEYS: trusted: Do not use WARN when encode fails\n\nWhen asn1_encode_sequence() fails, WARN is not the correct solution.\n\n1. asn1_encode_sequence() is not an internal function (located\n   in lib/asn1_encode.c).\n2. Location is known, which makes the stack trace useless.\n3. Results a crash if panic_on_warn is set.\n\nIt is also noteworthy that the use of WARN is undocumented, and it\nshould be avoided unless there is a carefully considered rationale to\nuse it.\n\nReplace WARN with pr_err, and print the return value instead, which is\nonly useful piece of information.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-36975"
                }
            ]
        }
    ]
}