{
    "type": "bundle",
    "id": "bundle--9b930b4c-1a22-4cd4-8c7c-d167d41845ff",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--27319eb9-0be3-46da-81da-5d5a807342d2",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-07-02T00:18:03.420064Z",
            "modified": "2024-07-02T00:18:03.420064Z",
            "name": "CVE-2024-39428",
            "description": "In trusty service, there is a possible out of bounds write due to a missing bounds check. This could lead to local denial of service with System execution privileges needed",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-39428"
                }
            ]
        }
    ]
}