{
    "type": "bundle",
    "id": "bundle--99c909b2-03a9-4a7c-aceb-f8ce845fe43f",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--0a8723d3-61f4-4559-874b-e900ad6695ba",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-05-03T00:16:57.026612Z",
            "modified": "2024-05-03T00:16:57.026612Z",
            "name": "CVE-2024-3955",
            "description": "URL GET parameter \"logtime\" utilized within the \"downloadlog\" function from \"cbpi/http_endpoints/http_system.py\" is subsequently passed to the \"os.system\" function in \"cbpi/controller/system_controller.py\" without prior validation allowing to execute arbitrary code.This issue affects CraftBeerPi 4: from 4.0.0.58 (commit 563fae9) before 4.4.1.a1 (commit 57572c7).\n\n",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-3955"
                }
            ]
        }
    ]
}