{
    "type": "bundle",
    "id": "bundle--043fd7a7-92a8-4898-bc27-055ef44c9156",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--7060272c-f3c0-4ced-8714-4049610b0cee",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-12-30T01:47:23.334484Z",
            "modified": "2024-12-30T01:47:23.334484Z",
            "name": "CVE-2024-56709",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nio_uring: check if iowq is killed before queuing\n\ntask work can be executed after the task has gone through io_uring\ntermination, whether it's the final task_work run or the fallback path.\nIn this case, task work will find ->io_wq being already killed and\nnull'ed, which is a problem if it then tries to forward the request to\nio_queue_iowq(). Make io_queue_iowq() fail requests in this case.\n\nNote that it also checks PF_KTHREAD, because the user can first close\na DEFER_TASKRUN ring and shortly after kill the task, in which case\n->iowq check would race.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-56709"
                }
            ]
        }
    ]
}