{
    "type": "bundle",
    "id": "bundle--436a8859-6e43-41d4-b092-ff6f99bad4e7",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--bd853f4d-ca9c-4301-8b9a-a8d36dd1cec9",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-07-02T00:18:03.407589Z",
            "modified": "2024-07-02T00:18:03.407589Z",
            "name": "CVE-2024-39427",
            "description": "In trusty service, there is a possible out of bounds write due to a missing bounds check. This could lead to local denial of service with System execution privileges needed",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-39427"
                }
            ]
        }
    ]
}