{
    "type": "bundle",
    "id": "bundle--1e7590b7-d724-429f-8998-5f22a6c92f6c",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--0f6d85bb-3223-4d1f-91f0-9b34563f1523",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-03-20T01:50:03.738762Z",
            "modified": "2025-03-20T01:50:03.738762Z",
            "name": "CVE-2024-25132",
            "description": "A flaw was found in the Hive hibernation controller component of OpenShift Dedicated. The ClusterDeployment.hive.openshift.io/v1 resource can be created with the spec.installed field set to true, regardless of the installation status, and a positive timespan for the spec.hibernateAfter value. If a ClusterSync.hiveinternal.openshift.io/v1alpha1 resource is also created, the hive hibernation controller will enter the reconciliation loop leading to a panic when accessing a non-existing field in the ClusterDeploymentâ€™s status section, resulting in a denial of service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-25132"
                }
            ]
        }
    ]
}