{
    "type": "bundle",
    "id": "bundle--c52ff548-07f2-4a0f-8d7f-58ae19fd06e2",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--06e545f5-8b59-400c-b23a-a403320dca50",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-06-18T00:18:01.454122Z",
            "modified": "2024-06-18T00:18:01.454122Z",
            "name": "CVE-2024-4032",
            "description": "The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-4032"
                }
            ]
        }
    ]
}