{
    "type": "bundle",
    "id": "bundle--952f223e-c9dc-497a-ae0e-d8178e809f6e",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--da56d6d2-3935-462e-b3d7-963ae7740096",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-05-23T00:16:50.372725Z",
            "modified": "2024-05-23T00:16:50.372725Z",
            "name": "CVE-2024-31904",
            "description": "IBM App Connect Enterprise 11.0.0.1 through 11.0.0.25 and 12.0.1.0 through 12.0.12.0 integration nodes could allow an authenticated user to cause a denial of service due to an uncaught exception.  IBM X-Force ID:  289647.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-31904"
                }
            ]
        }
    ]
}