{
    "type": "bundle",
    "id": "bundle--85a9820f-e45d-415c-b0bf-6408eed9ea9e",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--01ab03b6-b0a1-41fc-92f1-71d1a371ac0d",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-06-06T00:17:28.026117Z",
            "modified": "2024-06-06T00:17:28.026117Z",
            "name": "CVE-2024-5629",
            "description": "An out-of-bounds read in the 'bson' module of PyMongo 4.6.2 or earlier allows deserialization of malformed BSON provided by a Server to raise an exception which may contain arbitrary application memory.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-5629"
                }
            ]
        }
    ]
}