{
    "type": "bundle",
    "id": "bundle--a9fadb27-7b06-4c42-ac9c-ddd041e6cc88",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--d679f196-d429-4faf-abfa-c4f9800bf7c5",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-03T01:52:27.23906Z",
            "modified": "2025-04-03T01:52:27.23906Z",
            "name": "CVE-2025-30471",
            "description": "A validation issue was addressed with improved logic. This issue is fixed in visionOS 2.4, macOS Ventura 13.7.5, tvOS 18.4, iPadOS 17.7.6, iOS 18.4 and iPadOS 18.4, macOS Sequoia 15.4, macOS Sonoma 14.7.5. A remote user may be able to cause a denial-of-service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-30471"
                }
            ]
        }
    ]
}