{
    "type": "bundle",
    "id": "bundle--a39e88b5-914e-4b29-b52b-6268a8aee4a8",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--12340c32-12b7-4853-984d-b3114ce1b024",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-05-29T00:18:02.066869Z",
            "modified": "2024-05-29T00:18:02.066869Z",
            "name": "CVE-2024-3657",
            "description": "A flaw was found in 389-ds-base. A specially-crafted LDAP query can potentially cause a failure on the directory server, leading to a denial of service",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-3657"
                }
            ]
        }
    ]
}